plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'test/**/*'
    - 'spec/**/*'
    - 'Gemfile'
    - 'Rakefile'

# Disable style-only rules that don't affect functionality
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false  # Not critical for functionality

# Disable non-critical Rails rules
Rails/I18nLocaleTexts:
  Enabled: false  # Not critical for preventing bad code

Rails/HttpStatusNameConsistency:
  Enabled: false  # Warning only, not critical

Rails/StrongParametersExpect:
  Enabled: false  # Test-related, not critical

Rails/ApplicationRecord:
  Enabled: false  # Legacy models are fine

Rails/RakeEnvironment:
  Enabled: false  # Not critical

Style/RedundantConstantBase:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Layout/LineLength:
  Max: 200  # Increased limit to avoid false positives

Style/SoleNestedConditional:
  Enabled: false  # Not critical for preventing bad code

# Performance Rules - Critical for preventing bad queries and code optimization
Performance:
  Enabled: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'

# Essential Performance Cops for Code Optimization
Performance/Count:
  Enabled: true
  Description: 'Use count instead of size for counting records'

Performance/Detect:
  Enabled: true
  Description: 'Use detect instead of find.first'

Performance/StartWith:
  Enabled: true
  Description: 'Use start_with? instead of regex'

Performance/EndWith:
  Enabled: true
  Description: 'Use end_with? instead of regex'

Performance/RegexpMatch:
  Enabled: true
  Description: 'Use match? instead of =~ for better performance'

Performance/FlatMap:
  Enabled: true
  Description: 'Use flat_map instead of map.flatten'

Performance/MapCompact:
  Enabled: true
  Description: 'Use filter_map instead of map.compact'

Performance/Size:
  Enabled: true
  Description: 'Use size instead of count for arrays'

Performance/StringReplacement:
  Enabled: true
  Description: 'Use tr instead of gsub for single character replacements'

Performance/UnfreezeString:
  Enabled: true
  Description: 'Avoid unfreezing frozen strings'

# Rails-specific rules - Query Optimization Focus
Rails:
  Enabled: true

# Critical Query Optimization Cops
Rails/FindEach:
  Enabled: true
  Description: 'Use find_each instead of each to avoid loading all records into memory'

Rails/FindBy:
  Enabled: true
  Description: 'Use find_by instead of where.first'

Rails/InverseOf:
  Enabled: true
  Description: 'Prevent N+1 queries with inverse associations'

Rails/HasManyOrHasOneDependent:
  Enabled: true
  Description: 'Prevent orphaned records'

Rails/IndexBy:
  Enabled: true
  Description: 'Use index_by for efficient hash creation'

Rails/IndexWith:
  Enabled: true
  Description: 'Use index_with for efficient hash creation'

Rails/Pluck:
  Enabled: true
  Description: 'Use pluck instead of map when you only need specific attributes'

Rails/SkipsModelValidations:
  Enabled: true
  Description: 'Prevent skipping validations which can cause data issues'

# Additional Query Optimization Cops
# Note: Rails/EagerLoading and Rails/UnusedEagerLoading don't exist in rubocop-rails
# Use Bullet gem for N+1 query detection instead (already configured in CI)

Rails/WhereExists:
  Enabled: true
  Description: 'Use exists? instead of where(...).exists?'

Rails/WhereNot:
  Enabled: true
  Description: 'Use where.not instead of where with negative conditions'

# Additional Performance-Focused Style Rules
Style/HashSyntax:
  Enabled: true

Style/StringLiterals:
  Enabled: false  # Allow both single and double quotes

# Prevent common bad practices that affect performance
Style/GuardClause:
  Enabled: true
  Description: 'Use guard clauses for early returns'

Style/IfUnlessModifier:
  Enabled: true
  Description: 'Prefer modifier form for single-line conditionals'

# Disable non-performance style rules
Style/SymbolArray:
  Enabled: false  # Not performance-critical

Style/WordArray:
  Enabled: false  # Not performance-critical

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'db/migrate/**/*'

Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'db/migrate/**/*'

Metrics/ModuleLength:
  Max: 200

Metrics/ParameterLists:
  Max: 5

# Note: Rails/Unscoped cop doesn't exist in rubocop-rails
# Use custom query checks via rake task instead

# Summary: This configuration focuses on:
# 1. Performance optimization (Performance/* cops)
# 2. Query optimization (Rails/FindEach, Rails/Pluck, Rails/EagerLoading, etc.)
# 3. Code quality metrics that affect performance (AbcSize, MethodLength)
# 4. Minimal style rules (only those that impact performance)
